### PR TITLE
Adding a new build pom file to perform configuration and building of Rip...

### PR DESCRIPTION
**Pull request by ejzn**
...ple-UI. This adds a new build script in the form of a maven script to be executed by CI one every commit. This gives use the ability to build and create Ripple-UI from Hudson on every commit.

### CODE REVIEW

**Comment by ejzn** [comment]
@dansilivestru What is the possibility of adding a maven script to the root? This is to support ./configure and build from CI. It keeps us consistent with the rest of Ripple that currently uses maven. All it does is call the Jake, as well as an initial ./configure which we need to fetch resources in CI.

**Comment by gtanner** [comment]
I would vote that we don't pull this in as we already have a build system in place. Esp since all this does is call the existing build system.

**Comment by dansilivestru** [comment]
+1 on @gtanner comment.

**Comment by ejzn** [comment]
Hmm, alright. I've set up our CI server to build crx extensions automatically on any commit to a new internal webworks/Ripple repo that contains the B&D, Ripple-UI and NPAPI. I think it'll be handy for the future since things are slightly fragmented, but I'll look at another route. The reason I was putting it in here was that this project is a submodule of the webworks/Ripple repo.

**Comment by dansilivestru** [comment]
I see what you're saying. But this addition does not help anyone other then us internally at RIM. Anyone else cloning this project will not need this. That's why we're suggesting that we keep these kind of things internal to our RIM processes. Does that make sense?

**Comment by ejzn** [comment]
Of course it makes sense. I was attempting to reduce the amount of Ripple-UI forks. But I can go ahead and fork it again internally, so I'll make our internal process at least when we develop to work off a fork, then we will push upstream changes into this repo + the public facing one.

Now that I mention it, I opened this in the wrong place I meant to open it against blackberry-webworks/Ripple-UI. But I suspect it will be the same result.

**Comment by dansilivestru** [comment]
you could consider having it on your local fork and just add it to the .gitignore file so it doesn't make it into the public repo?

**Comment by ejzn** [comment]
No this will be used by SCM and CI, so I'd like to keep it in the main repo since it will be used for actually building the CRX file. That's fine I'll just fork it then.

**Pull request closed without merging**
