### PR TITLE
Removed dependency on jasmine-node (npm package). Bumped jasmine submodule to v1.1.0.

### PR DESCRIPTION
**Pull request by brentlintner**
See commit for details. This should help simplify our testing with jasmine at least.

My favourite part is how it now logs things like:

``` javascript
geo
  it encountered a declaration exception
    message: Error: Cannot find module 'sffs'
    trace: Error: Cannot find module 'sffs'
    at Function._resolveFilename (module.js:326:11)
    at Function._load (module.js:271:25)
    at require (module.js:355:19)
    at [object Object].<anonymous> (/home/brent/src/ripple-ui/test/unit/geo.js:21:9)
    at [object Object].describe (/home/brent/src/ripple-ui/thirdparty/jasmine/lib/jasmine-core/jasmine.js:791:21)
    at /home/brent/src/ripple-ui/thirdparty/jasmine/lib/jasmine-core/jasmine.js:575:27
    at Object.<anonymous> (/home/brent/src/ripple-ui/test/unit/geo.js:16:1)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
```

Thoughts (everyone)? :-)

### CODE REVIEW

**Comment by brentlintner** [comment]
As a side note, this was something I got carried away with when I was talking to @dbrgss regarding Jasmine JSUnit XML output support in newer versions of Jasmine for the CI server, and how the frozen version of jasmine-node might be an issue. Also, the duplication of jasmine has always irked the hell of out me. :-D This should be a stepping stone to allowing that output to be implemented.

Dave, IMO might be best to create a separate GitHub issue for outputting to JSUnit XML via the `jake test` namespace of something. (assuming it's available in a certain release of Jasmine we can get working). :-)

**Comment by brentlintner** [comment]
Gah. I was reviewing some more and I missed logging the total test time. I'll implement that, then post again when it's complete.

**Comment by brentlintner** [comment]
Ok, updated it to log the total test time as well. Open to any tweaks etc but it seems quite solid. I'd appreciate any reviews, as I plan to merge this in asap (hopefully today).

Thanks!

**Comment by brentlintner** [comment]
Wow. Spelling fail in that last commit. I know it's taboo.. but I have rebased and force pushed!

**Comment by gtanner** [comment]
Seems good to me

**Comment by brentlintner** [comment]
Thanks for the look over @gtanner.

Oh, one nitpick I sort of left for now btw, is that the `trace:` attribute usually has the `message:` included in it (see my example in description), but rarely this is not the case (i.e. if there is a `throw "foo":` in the code). For the time being I just left it verbosely duplicating those lines if that's ok with everyone.

**Pull request merged**
