### PR TITLE
added console.clear() and removed unneeded call to widgetConfig.initializ...

### PR DESCRIPTION
**Pull request by dansilivestru**
...e from emulatorBridge

### CODE REVIEW

**Comment by brentlintner** [comment]
Spelling fix needed in message. Also, the two diffs don't go together (ideally, they should be separate commits).

**Comment by brentlintner** [comment]
Also, (as a personal nitpick on the messages) I am not sure _why_ these things were done from the message. :-)

i.e. If you want to (it is a small commit), but: Why was the call not needed? And, why should there be a console.clear?

**Comment by dansilivestru** [comment]
Cleaned things up as suggested

**Comment by brentlintner** [comment]
Epic! Looks good to me (+1). :-)

**Pull request merged**
