### PR TITLE
release for v0.9.12

### PR DESCRIPTION
**Pull request by dansilivestru**

### CODE REVIEW

**Comment by brentlintner** [comment]
I'm pretty sure this can be closed, now (?).

**Comment by horacelin** [comment]
Somebody has to teach me how to use this new "Cross Domain Proxy" setting? My Ajax cross domain requests no longer working! I used to "enable" the settings, now there are "local" and "remote" ??? Anyway, none of them working for me! BB Playbook is the target I used.

**Comment by dansilivestru** [comment]
@horacelin you will most like want to user remote. Can you please share your Ajax code with us? What URL are you trying to make requests to? Also, are you seeing anything in the JavaScrip console?

**Comment by horacelin** [comment]
Thanks for the quick response -

We use dojo to do Ajax request,
url is "https://portal.posincloud.com/MobilePOS/api/setup"

++++++++++++++++++++++++++++++++++++++++++++++
function checkTokenRight(){
var tokn = getLocal('clientToken');
if(tokn === null)return;
var tokenInf = {"token":tokn,"confirmWrite":"N"};
var xhrArgs = {
        url: "https://portal.posincloud.com/MobilePOS/api/setup",
        postData: dojo.toJson(tokenInf),
        handleAs: "json",
        headers: {"Content-Type":"application/json"},
        preventCache: true,
        load: function(data){        
    if(data.devInfo!=null&&data.devInfo.id!=="playbook"){
    alert(lang[language]['dlgDeviceMismatch']);
    //close app
            if (navigator.app && navigator.app.exitApp) {
                navigator.app.exitApp();
            } else if (navigator.device && navigator.device.exitApp) {
            navigator.device.exitApp();
            }
    }
        },
        error: function(error){
            alert(lang[language]["msgUnexpectedErr"] + error);
        }
        }
        var deferred = dojo.xhrPost(xhrArgs);
}

+++++++++++++++++++++++++++++++++++++++++++++++++
It failed on http request too -
http://pos.couchone.com/greenleaf (no id or password needed)

if (couchproxy === 1){
localhost = "pos.couchone.com";
dbname = "greenleaf";
}
    var xhrArgs = {
        url: 'http://'+localhost+'/'+dbname,
    handleas: 'json',
    user: userid,
    password: userpass,
    load: function(data){
       dlog("local database found!");
            var res = JSON.parse(data);
            db2mem();
        },
        error: function(err){
      //       alert(JSON.stringify(err.responseText));
        if (JSON.stringify(err).indexOf("not_found") > -1) {   
        dlog("local database NOT found!");
}
            }
}
var deferred = dojo.xhrGet(xhrArgs);
}

**Comment by horacelin** [comment]
we had no prob with previous version (just need to disabled the id and password for ajax request)
http://mystonetool.blogspot.com/

**Comment by brentlintner** [comment]
@horacelin could you try clearing your browser's cache (a long shot, but might work, as it was an issue with someone else, I understand)?

**Pull request closed without merging**
