### PR TITLE
Build script for continuous integration

### PR DESCRIPTION
**Pull request by nukulb**
Simple bash script to grab the output of jake and jake test and zip the build output to create build_output folder which acts as Artifacts folder for the Hudson CI server.

### CODE REVIEW

**Comment by brentlintner** [comment]
Oh, btw can you update this pull request to pull into the "next" branch as per workflow (no pull requests, unless for hotfixes should go into master). I am creating one now.

**Comment by nukulb** [comment]
1. good point, do you think build/scripts/build.sh is better or just scripts/build.sh?
2. I will remove those debug statements.
3. Its only valuable if you think anyone else except for my Continuous Integration system will be calling it because the CI system is not going to be committing anything and all the ignoring of the artifacts is auto-magically handled by Hudson. I can add it if you like but as far as CI is concerned there is no advantage. Thoughts?

I can update this to next but I wanted this script to exist in both master and next because we want to have two CI builds one for the master branch and one for the next branch.

**Comment by nukulb** [comment]
And because I want this change in both master and next, what is the process of getting it in both right away?

**Comment by brentlintner** [comment]
1 IMO I think build/scripts is more ideal since it keeps a more succinct root directory, groups build oriented code, and still reads good. That's my opinion (and reason) though. :-)

3 Good point. It was more of a proactive nitpick (given others would use the script).. YAGNI? ;-)

Regarding the need to be in both branches, thanks for the info, I see what you mean. In hind sight it does not seem right to keep it in "next" until a version release.

Others please chime in if they have alternative ideas on workflow, but my thought would be to treat this as a "hotfix", and merge into master, since it is not a release oriented feature, nor a bug.

I.e. akin to this build fix https://github.com/blackberry/Ripple-UI/commit/402ca6d8379f427518873a8218ae173ab9d97789

I am just working on an initial "next" branch today (in tinyhippos), but if no one objects I think this could be merged into master before that pull request is issued, and the script will be in both branches.

**Comment by brentlintner** [comment]
Oops, one more thing.

@kwallis I presume this file should have a Apache 2.0 license notice at the top?

**Comment by nukulb** [comment]
agreed on all counts, I will update the scripts and the CI. Once this change is in I will send out the details on where the CI currently is located and what the plans for improvement are.

**Comment by kwallis** [comment]
Yup, should have Apache 2.0. ;)

**Comment by nukulb** [comment]
The configure script also doesn't have one so I didn't there was any point including it, seems like build scripts normally don't have this license on top. I personally don't think it makes sense for scripts to have this but I can put it in if its a legal requirement.
If yes then the configure script should also have it.

**Comment by nukulb** [comment]
I have included the license as well.
Updated all the changes. 
When this is committed into master, someone needs to then put this into next as well. I can't complete the first increment of CI till that is ready. So sooner will be better, please.

**Comment by brentlintner** [comment]
Ah, that is right.. configure doesn't have one :-s. Having it in there seemed a bit extraneous (IMO specially for a small, generic dependency install script similarly used in other OSS projects). So I can't say I disagree with your points. I think it may be a legal requirement for any file, regardless... So, If need be I will add a task to also add the notice to the configure script (asap).

**Comment by kwallis** [comment]
I understand the points.  Let's just be safe for now and put it in.

**Comment by dansilivestru** [comment]
Ok so the configure script is going to be a separate pull request. Brent, can you pull this into master and then rebase the next branch. Just talking to Nukul and Ken on this. Seems like it's good to go.

**Comment by brentlintner** [comment]
That was my plan. :-) I have not pushed commits to the "next" branch yet either, so we don't need to rebase. I also created a task to add notice to configure script.

**Comment by brentlintner** [comment]
PS Nukul I don't think you removed (or mv'd) the script file (still showing up in the overall diffs).

**Comment by nukulb** [comment]
Sorry about that, its my fault. I am developing on the build machine but I am still committing from my mac, so very easy to miss stuff.

**Pull request merged**
