### PR TITLE
Issue #577 bugfix on Cordova 2.0.0 FileWriter

### PR DESCRIPTION
**Pull request by windameister**
see https://github.com/blackberry/Ripple-UI/pull/584

Close the previous one and changed pull request to next 
(already signed as official contributor now) @brentlintner

### CODE REVIEW

**Comment by brentlintner** [comment]
@windameister awesome! I was about to merge this in, but noticed that there are failing tests for that module. I am going to try and fix them myself (when I can), but if you can fix those up as well, that would be greatly appreciated!!

**Comment by windameister** [comment]
@brentlintner  Sorry for missing the unit-test by myself, I'll try to figure it out as soon as possible. : )

**Comment by windameister** [comment]
@brentlintner  I think it is the test case passing the wrong argument caused the mistake.
ref here: https://github.com/apache/incubator-cordova-ios/blob/master/bin/templates/project/www/cordova-2.2.0rc1.js : 2980
=====> cordova call File.write with the argument as below:
    exec(s, e, "File", "write", [this.fileName, text, this.position]);

while in our test case:
=====>
    file.write(s, e, [_fileEntry, text, position]);

cordova.js : 2853, 

```
var FileWriter = function(file) {
    this.fileName = "";
    this.length = 0;
    if (file) {
        this.fileName = file.fullPath || file;    // <--------- this  line
        // file do not have fullPath made this.fileName be "file" object, now not happening
        this.length = file.size || 0;
    }
```

After I've changed the getFileMetadata function's return value, The test case does not work in the same way as cordova FileWriter does.

I think the unit test should be changed to:
file.write(s, e, [_fileEntry.fullPath, text, position]);

**Comment by brentlintner** [comment]
Thanks a bunch for figuring out the unit test issue @windameister, and thanks again for the bug fix. I merged this in just now. I also squashed all 3 commits into one [commit](https://github.com/blackberry/Ripple-UI/commit/5115b8aac7e35d13da1ffa4fb13d846ef650066b), as well (for form)- hope you do not mind. :-)

**Pull request closed without merging**
