### PR TITLE
Add PhoneGap plugin

### PR DESCRIPTION
**Pull request by natsumesou**
Add PhoneGap plugin function.
This is able to set PhoneGap plugin response json code on Ripple panel.

### CODE REVIEW

**Comment by natsumesou** [comment]
This is my first commit for open source project.
so if this commit has any problem, please tell and teach me.

**Comment by kwallis** [comment]
Thanks very much for the contribution!  While we take a look at it and review it, please check out the contribution documentation at:

http://blackberry.github.com/howToContribute.html

We will need you to complete and send an ICLA, and if required, a CCLA from your company.  Meanwhile, we will check this out!  Sounds interesting at the high level.

Thanks!

**Comment by natsumesou** [comment]
ok. i sent it.
please check it !

**Comment by ndaversa** [comment]
Looks like this will need a rebase.

Also I think this should be a pull request against the 'next' branch, not 'master'

**Comment by gtanner** [comment]
Hey,

Check out the latest build of Ripple. We handled phonegap plugin's a little differently:
https://github.com/blackberry/Ripple-UI/blob/master/lib/ripple/platform/cordova/1.6/bridge.js#L39

We will prompt for the JSON to return and weather to call the success / fail callback

**Pull request closed without merging**
