### PR TITLE
Version 0.9.13

### PR DESCRIPTION
**Pull request by dansilivestru**

### CODE REVIEW

**Comment by brentlintner** [comment]
Looks good to me. +1. :-)

Yay, new device skins!

**Comment by szuzul** [comment]
Hi, when can we expect to upload ripple extension to 0.9.13 directly from chrome://extensions/, currently there is only 0.9.12 available ?..

**Comment by dansilivestru** [comment]
The plan is to release it to the chrome store and to the blackberry
developer site tomorrow.

Dan Silivestru
+1 (519)-589-3624

On 2013-02-04, at 17:27, szuzul notifications@github.com wrote:

Hi, when can we expect to upload ripple extension to 0.9.13 directly from
chrome://extensions/, currently there is only 0.9.12 available ?..

—
Reply to this email directly or view it on
GitHubhttps://github.com/blackberry/Ripple-UI/pull/710#issuecomment-13103460.

**Comment by szuzul** [comment]
That's cool, thanks... I'm also having xhr_proxy error in options and get request in my backbone app.

**Comment by dansilivestru** [comment]
Can you share some code with us? I would suggest you open a new issue with
code sample and steps to reproduce.

Thanks,

Dan Silivestru
+1 (519)-589-3624

On 2013-02-04, at 19:09, szuzul notifications@github.com wrote:

That's cool, thanks... I'm also having xhr_proxy error in options and get
request in my backbone app.

—
Reply to this email directly or view it on
GitHubhttps://github.com/blackberry/Ripple-UI/pull/710#issuecomment-13107799.

**Comment by szuzul** [comment]
It isn't xhr_proxy error as i can see now. it is something in relation with time out response in case of ripple and require.js... I'll open new issue.

**Pull request merged**
